# Generated by Django 5.2.1 on 2025-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(choices=[('Mirpur 10', 'Mirpur 10'), ('Pallabi', 'Pallabi'), ('Kazipara', 'Kazipara'), ('Agargaon', 'Agargaon'), ('Uttara', 'Uttara'), ('Bijoy soroni', 'Bijoy soroni'), ('Rupnagar', 'Rupnagar'), ('Other', 'Other')], max_length=200, null=True)),
            ],
        ),
    ]
