# Generated by Django 5.2.1 on 2025-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0002_reportsubmission_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.CharField(choices=[('Mirpur 10', 'Mirpur 10'), ('Pallabi', 'Pallabi'), ('Kazipara', 'Kazipara'), ('Agargaon', 'Agargaon'), ('shewrapara', 'shewrapara'), ('Uttara', 'Uttara'), ('Bijoy soroni', 'Bijoy soroni'), ('Rupnagar', 'Rupnagar'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
