# Generated by Django 5.2.1 on 2025-06-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0003_remove_review_email_alter_review_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
