# Generated by Django 5.2.1 on 2025-06-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0004_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RePortall.customer'),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='Review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RePortall.review'),
        ),
    ]
