# Generated by Django 5.2.1 on 2025-06-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0006_rename_customer_reportsubmission_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubmission',
            name='date_created',
        ),
    ]
