# Generated by Django 5.2.1 on 2025-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0007_remove_reportsubmission_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='RePortall.tag'),
        ),
    ]
