# Generated by Django 5.2.1 on 2025-06-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0010_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
