# Generated by Django 5.2.1 on 2025-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RePortall', '0011_remove_review_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
